version: "3.8"

services:
  traefik:
    image: "traefik:v2.4.8"
    ports:
      - "443:443"
    volumes:
      - "./traefik.yaml:/etc/traefik/traefik.yaml:ro"
      - "./letsencrypt:/letsencrypt"
      - "/var/run/docker.sock:/var/run/docker.sock:ro"
    restart: unless-stopped

  whoami:
    image: docker.io/traefik/whoami:latest
    labels:
      - "traefik.http.routers.whoami.rule=Host(`mail.zweili.org`)"

  mail:
    image: docker.io/mailserver/docker-mailserver:9.1.0
    hostname: mail
    domainname: zweili.org
    env_file: mailserver.env
    # To avoid conflicts with yaml base-60 float, DO NOT remove the quotation marks.
    ports:
      - "25:25"
      - "143:143"
      - "587:587"
      - "993:993"
    volumes:
      - ./letsencrypt:/etc/letsencrypt
      - ./maildata:/var/mail
      - ./mailstate:/var/mail-state
      - ./maillogs:/var/log/mail
      - ./config/:/tmp/docker-mailserver/
      - /etc/localtime:/etc/localtime:ro
    restart: unless-stopped
    cap_add: ["NET_ADMIN", "SYS_PTRACE"]
