version: "3.8"

services:
  mail:
    image: docker.io/mailserver/docker-mailserver:11.0.0
    hostname: mail
    domainname: zweili.org
    env_file: mailserver.env
    # To avoid conflicts with yaml base-60 float, DO NOT remove the quotation marks.
    ports:
      - "25:25"
      - "143:143"
      - "587:587"
      - "993:993"
    volumes:
      - ../rainloop/letsencrypt/acme.json:/etc/letsencrypt/acme.json:ro
      - mail/maildata:/var/mail
      - mail/mailstate:/var/mail-state
      - mail/sa-learn:/etc/cron.d/sa-learn
      - mail/maillogs:/var/log/mail
      - mail/config/:/tmp/docker-mailserver/
      - /etc/localtime:/etc/localtime:ro
    restart: unless-stopped
    cap_add: ["NET_ADMIN", "SYS_PTRACE"]

  whoami:
    image: docker.io/traefik/whoami:latest
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.whoami.rule=Host(`mail.zweili.org`)"
      - "traefik.http.routers.whoami.entrypoints=websecure"
      - "traefik.http.routers.whoami.tls.certresolver=myresolver"
      - "traefik.http.routers.whoami.middlewares=default-headers@file"

volumes:
  mail:
    driver_opts:
      type: "nfs"
      o: "addr=10.7.89.108,nolock,hard,rw,vers=4.1"
      device: ":/server_data/mail"
