version: "3.8"

services:
  letsencrypt:
    image: linuxserver/letsencrypt
    container_name: letsencrypt
    cap_add:
      - NET_ADMIN
    env_file: letsencrypt.env
    volumes:
      - ./letsencrypt:/config
    ports:
      - 80:80
      - 443:443
    restart: unless-stopped

  mail:
    image: docker.io/mailserver/docker-mailserver:9.1.0
    hostname: mail
    domainname: zweili.org
    env_file: mailserver.env
    # To avoid conflicts with yaml base-60 float, DO NOT remove the quotation marks.
    ports:
      - "25:25"
      - "143:143"
      - "587:587"
      - "993:993"
    volumes:
      - ./letsencrypt/etc/letsencrypt:/etc/letsencrypt
      - ./maildata:/var/mail
      - ./mailstate:/var/mail-state
      - ./maillogs:/var/log/mail
      - ./config/:/tmp/docker-mailserver/
      - /etc/localtime:/etc/localtime:ro
    restart: unless-stopped
    cap_add: ["NET_ADMIN", "SYS_PTRACE"]
