version: "3"

services:
  jdownloader:
    image: jaymoulin/jdownloader@sha256:dcca7602fb8dae1e4f14b272d553219964be3d4bc957e35a6ad300067ccfccac #2.0.3-amd64
    restart: always
    user: 1000:100
    volumes:
      - jdownloader:/opt/JDownloader/app/cfg
      - downloads:/opt/JDownloader/app/Downloads
      - jdownloader:/opt/JDownloader/app/logs #optional
      - /etc/localtime:/etc/localtime:ro #optional
    environment:
      - MYJD_USER
      - MYJD_PASSWORD
    ports:
      - 3129:3129

volumes:
  jdownloader:
    driver_opts:
      type: "nfs"
      o: "addr=10.7.89.108,nolock,soft,rw,vers=4.1"
      device: ":/server_data/jdownloader"

  downloads:
    driver_opts:
      type: "nfs"
      o: "addr=10.7.89.108,nolock,soft,rw,vers=4.1"
      device: ":/media/downloads"
