version: "2"

services:
  rainloop:
    image: hiloyt/rainloop
    container_name: rainloop
    volumes:
      - rainloopdata:/rainloop/data
    ports:
      - "8080:80"
    restart: unless-stopped
    links:
      - db:db

  db:
    image: mariadb
    restart: unless-stopped
    volumes:
      - ./db:/var/lib/mysql
    environment:
      - MYSQL_ROOT_PASSWORD
      - MYSQL_PASSWORD
      - MYSQL_DATABASE
      - MYSQL_USER

volumes:
  rainloopdata:
    driver_opts:
      type: "nfs"
      o: "addr=10.7.89.108,nolock,hard,rw,vers=4.1"
      device: ":/server_data/docker-mailserver/rainloopdata"
