version: "2"
volumes:
  db:

services:
  traefik:
    image: "traefik:v2.2"
    ports:
      - "443:443"
    volumes:
      - "./traefik.yaml:/etc/traefik/traefik.yaml:ro"
      - "./letsencrypt:/letsencrypt"
      - "/var/run/docker.sock:/var/run/docker.sock:ro"

  rainloop:
    image: hardware/rainloop
    container_name: rainloop
    volumes:
      - ./data:/rainloop/data
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.rainloop.rule=Host(`${APP_DOMAIN}`)"
      - "traefik.http.routers.rainloop.entrypoints=websecure"
      - "traefik.http.routers.rainloop.tls.certresolver=myresolver"
    restart: unless-stopped
    links:
      - db:db

  db:
    image: mariadb
    restart: unless-stopped
    volumes:
      - db:/var/lib/mysql
    environment:
      - "MYSQL_ROOT_PASSWORD=${MYSQL_ROOT_PASSWORD}"
      - "MYSQL_PASSWORD=${MYSQL_PASSWORD}"
      - "MYSQL_DATABASE=${MYSQL_DATABASE}"
      - "MYSQL_USER=${MYSQL_USER}"
