version: "2"

services:
  traefik:
    image: "traefik:v2.2"
    ports:
      - "4430:443"
    volumes:
      - "./traefik.yaml:/etc/traefik/traefik.yaml:ro"
      - "./letsencrypt:/letsencrypt"
      - "/var/run/docker.sock:/var/run/docker.sock:ro"
    restart: unless-stopped

  rainloop:
    image: hiloyt/rainloop
    container_name: rainloop
    volumes:
      - mail/rainloopdata:/rainloop/data
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.rainloop.rule=Host(`${APP_DOMAIN}`)"
      - "traefik.http.routers.rainloop.entrypoints=websecure"
      - "traefik.http.routers.rainloop.tls.certresolver=myresolver"
      - "traefik.http.routers.rainloop.middlewares=default-headers@file"
    restart: unless-stopped
    links:
      - db:db

  db:
    image: mariadb
    restart: unless-stopped
    volumes:
      - ./db:/var/lib/mysql
    environment:
      - MYSQL_ROOT_PASSWORD
      - MYSQL_PASSWORD
      - MYSQL_DATABASE
      - MYSQL_USER

volumes:
  mail:
    driver_opts:
      type: "nfs"
      o: "addr=10.7.89.108,nolock,hard,rw,vers=4.1"
      device: ":/server_data/mail"
