---
version: "3"
services:
  heimdall:
    image: linuxserver/heimdall
    container_name: heimdall
    environment:
      - PUID=1000
      - PGID=100
      - TZ=Europe/Zurich
    volumes:
      - heimdall:/config
    restart: unless-stopped
    ports:
      - 8081:80

volumes:
  heimdall:
    driver_opts:
      type: "nfs"
      o: "addr=10.7.89.108,nolock,hard,rw,noatime"
      device: ":/server_data/heimdall"
