version: "3"
services:
  plex:
    container_name: plex
    image: plexinc/pms-docker
    restart: unless-stopped
    environment:
      - TZ
      - PLEX_CLAIM
    network_mode: host
    volumes:
      - ./config:/config
      - ./tmp:/transcode
      - media:/mnt/media

volumes:
  media:
    driver_opts:
      type: "nfs"
      o: "addr=10.7.89.108,nolock,hard,rw,noatime"
      device: ":/media"
