homeserver:
  address: http://synapse:8008
  domain: example.com
  appservice:
  address: http://whatsapp-bridge:29318
  hostname: 0.0.0.0
  port: 29318
  database:
  	type: postgres
    uri: host=db user=synapse password=foo dbname=whatsapp-bridge sslmode=disable
    max_open_conns: 20
    max_idle_conns: 2
  state_store_path: ./mx-state.json
  id: 2li-whatsapp-bridge
    bot:
      username: whatsappbot
      displayname: WhatsApp bridge bot
      avatar: mxc://maunium.net/NeXNQarUbrlYBiPCpprYsRqr
    as_token: foo
    hs_token: bar
  bridge:
    username_template: whatsapp_{{.}}
    displayname_template: '{{if .Notify}}{{.Notify}}{{else}}{{.Jid}}{{end}} (WA)'
    community_template: whatsapp_{{.Localpart}}={{.Server}}
    connection_timeout: 20
    login_qr_regen_count: 2
    max_connection_attempts: 3
    connection_retry_delay: -1
    report_connection_retry: true
    contact_wait_delay: 1
    initial_chat_sync_count: 10
    initial_history_fill_count: 20
    recovery_chat_sync_count: -1
    recovery_history_backfill: true
    sync_max_chat_age: 259200
    sync_with_custom_puppets: true
    invite_own_puppet_for_backfilling: true
    private_chat_portal_meta: false
    allow_user_invite: false
    command_prefix: '!wa'
    permissions:
      '@username:example.com': 100
      example.com: 10
  logging:
    directory: ./logs
    file_name_format: '{{.Date}}-{{.Index}}.log'
    file_date_format: "2006-01-02"
    file_mode: 384
    timestamp_format: Jan _2, 2006 15:04:05
    print_level: debug
