version: "2"

services:
  gitea:
    # https://hub.docker.com/r/gitea/gitea/tags
    image: gitea/gitea:1.17.3
    environment:
      - USER_UID
      - USER_GID
      - "DB_TYPE=mysql"
      - "DB_HOST=host.docker.internal:3306"
      - "DB_NAME=giteadb"
      - "DB_USER=gitea"
      - DB_PASSWD
      - "ROOT_URL=git.2li.ch"
      - "INSTALL_LOCK=true"
      - SECRET_KEY
      - "DISABLE_REGISTRATION=true"
    volumes:
      - gitea_data:/data
      - /etc/timezone:/etc/timezone:ro
      - /etc/localtime:/etc/localtime:ro
    ports:
      - "2222:22"
      - "8080:3000"
    extra_hosts:
      - "host.docker.internal:host-gateway"
    restart: unless-stopped

volumes:
  gitea_data:
    driver_opts:
      type: "nfs"
      o: "addr=10.7.89.108,nolock,hard,rw,vers=4.1,noatime"
      device: ":/server_data/gitea/data"
