version: "2"

services:
  redis:
    image: redis:alpine
    restart: unless-stopped

  app:
    build: ./nextcloud
    environment:
      - MYSQL_PASSWORD
      - "MYSQL_DATABASE=nextcloud"
      - "MYSQL_USER=nextcloud"
      - "MYSQL_HOST=172.17.0.1"
      - "NEXTCLOUD_ADMIN_USER=thedoctor"
      - NEXTCLOUD_ADMIN_PASSWORD
      - "NEXTCLOUD_TRUSTED_DOMAINS=nextcloud.2li.ch nextcloud2.2li.local 10.7.89.103"
      - "REDIS_HOST=redis"
      - "SMTP_HOST=mail.infomaniak.com"
      - "SMTP_SECURE=ssl"
      - "SMTP_PORT=587"
      - "SMTP_NAME=admin@2li.ch"
      - SMTP_PASSWORD
      - "MAIL_FROM_ADDRESS=admin@2li.ch"
    depends_on:
      - redis
    volumes:
      - nextcloud_data:/var/www/html
      - ./custom-php.ini:/usr/local/etc/php/conf.d/zzz-custom.ini
    ports:
      - 8080:80
    extra_hosts:
      - "host.docker.internal:host-gateway"
    restart: unless-stopped

  cron:
    image: nextcloud@sha256:e46cb7adc2015f7a464611a2fbcfe37f3bfbf8c5d9afb0c584b131fadb8014b6:23.0.10-apache
    restart: unless-stopped
    volumes:
      - nextcloud_data:/var/www/html
    entrypoint: /cron.sh
    depends_on:
      - redis
    extra_hosts:
      - "host.docker.internal:host-gateway"

volumes:
  nextcloud_data:
    driver_opts:
      type: "nfs"
      o: "addr=10.7.89.108,nolock,hard,rw,vers=4.1,noatime"
      device: ":/server_data/nextcloud/data"
