version: "2"

services:
  redis:
    image: redis:alpine
    restart: unless-stopped

  app:
    build: ./nextcloud
    environment:
      - MYSQL_PASSWORD
      - "MYSQL_DATABASE=nextcloud"
      - "MYSQL_USER=nextcloud"
      - "MYSQL_HOST=172.17.0.1"
      - "NEXTCLOUD_ADMIN_USER=thedoctor"
      - NEXTCLOUD_ADMIN_PASSWORD
      - "NEXTCLOUD_TRUSTED_DOMAINS=nextcloud.2li.ch nextcloud2.2li.local 10.7.89.103"
      - "REDIS_HOST=redis"
      - "SMTP_HOST=mail.infomaniak.com"
      - "SMTP_SECURE=ssl"
      - "SMTP_PORT=465"
      - "SMTP_NAME=admin@zweili.ch"
      - SMTP_PASSWORD
      - "MAIL_FROM_ADDRESS=admin@zweili.ch"
    depends_on:
      - redis
    volumes:
      - nextcloud_data:/var/www/html
      - ./custom-php.ini:/usr/local/etc/php/conf.d/zzz-custom.ini
    ports:
      - 8080:80
    extra_hosts:
      - "host.docker.internal:host-gateway"
    restart: unless-stopped

  cron:
    # https://hub.docker.com/_/nextcloud/tags?page=1&name=apache
    image: nextcloud:25.0.0-apache@sha256:c65b3a099746f9168a594adc84f586a6a40719f50889d7814a6b68f6e183b26b
    restart: unless-stopped
    volumes:
      - nextcloud_data:/var/www/html
    entrypoint: /cron.sh
    depends_on:
      - redis
    extra_hosts:
      - "host.docker.internal:host-gateway"

volumes:
  nextcloud_data:
    driver_opts:
      type: "nfs"
      o: "addr=10.7.89.108,nolock,hard,rw,vers=4.1,noatime"
      device: ":/server_data/nextcloud/data"
