ersion: '3.0'

services:
  # PHP FPM Server
  php:
    image: ghcr.io/nebucatnetzer/snappymail-aarch64/snappymail:latest
    volumes:
      - ./src:/var/www
      - ./snappymail.ini:/usr/local/etc/php/conf.d/snappymail.ini
    extra_hosts:
      - "host.docker.internal:host-gateway"

  # Nginx load balancer translating to PHP FPM
  nginx:
    image: nginx:latest
    hostname: nginx
    depends_on:
      - php
    ports:
      - "8080:80"
    volumes:
      - ./src:/var/www
      - ./snappy_nginx.conf:/etc/nginx/conf.d/default.conf
