---
version: "2"

services:
  tt-rss:
    image: registry.gitlab.com/lunik1/docker-tt-rss
    container_name: tt-rss
    environment:
      - PUID
      - PGID
      - TZ
      - TTRSS_DB_TYPE
      - "TTRSS_DB_USER=${MYSQL_USER}"
      - "TTRSS_DB_NAME=${MYSQL_DATABASE}"
      - "TTRSS_DB_PASS=${MYSQL_PASSWORD}"
      - TTRSS_DB_PORT
      - TTRSS_DB_HOST=db
      - "TTRSS_SELF_URL_PATH=https://${APP_DOMAIN}"
    volumes:
      - tt-rss:/config
    depends_on:
      - db
    links:
      - db:db
    ports:
      - "8080:80"
    restart: always

  db:
    image: mariadb:10.3-bionic
    command: --transaction-isolation=READ-COMMITTED --binlog-format=ROW
    restart: always
    volumes:
      - ./db:/var/lib/mysql
    environment:
      - MYSQL_ROOT_PASSWORD
      - MYSQL_PASSWORD
      - MYSQL_DATABASE
      - MYSQL_USER

volumes:
  tt-rss:
    driver_opts:
      type: "nfs"
      o: "addr=10.7.89.108,nolock,hard,rw,vers=4.1"
      device: ":/server_data/ttrss/config"
