---
version: "2"

services:
  tt-rss:
    image: registry.gitlab.com/lunik1/docker-tt-rss
    container_name: tt-rss
    environment:
      - PUID
      - PGID
      - "TZ=Europe/Zurich"
      - "TTRSS_DB_TYPE=mysql"
      - "TTRSS_DB_USER=ttrss"
      - "TTRSS_DB_NAME=ttrssdb"
      - TTRSS_DB_PASS
      - "TTRSS_DB_PORT=3306"
      - "TTRSS_DB_HOST=host.docker.internal"
      - "TTRSS_SELF_URL_PATH=https://ttrss.2li.ch"
    volumes:
      - ./config:/config
    ports:
      - "8080:80"
    extra_hosts:
      - "host.docker.internal:host-gateway"
    restart: always
