---
version: "2"

services:
  traefik:
    image: "traefik:v2.2"
    ports:
      - "443:443"
    volumes:
      - "./traefik.yaml:/etc/traefik/traefik.yaml:ro"
      - "./letsencrypt:/letsencrypt"
      - "/var/run/docker.sock:/var/run/docker.sock:ro"
    restart: unless-stopped

  tt-rss:
    image: registry.gitlab.com/lunik1/docker-tt-rss@sha256:35dc2dc3697e8c88cb57fbfaf6313ef41bf8fa6583dbb650e9e752587bb7b967
    container_name: tt-rss
    environment:
      - PUID
      - PGID
      - TZ
      - TTRSS_DB_TYPE
      - "TTRSS_DB_USER=${MYSQL_USER}"
      - "TTRSS_DB_NAME=${MYSQL_DATABASE}"
      - "TTRSS_DB_PASS=${MYSQL_PASSWORD}"
      - TTRSS_DB_PORT
      - TTRSS_DB_HOST=db
      - "TTRSS_SELF_URL_PATH=https://${APP_DOMAIN}"
    volumes:
      - ./config:/config
    depends_on:
      - db
    links:
      - db:db
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.ttrss.rule=Host(`${APP_DOMAIN}`)"
      - "traefik.http.routers.ttrss.entrypoints=websecure"
      - "traefik.http.routers.ttrss.tls.certresolver=myresolver"
      - "traefik.http.routers.ttrss.middlewares=default-headers@file"
    restart: always

  db:
    image: mariadb:10.3-bionic
    command: --transaction-isolation=READ-COMMITTED --binlog-format=ROW
    restart: always
    volumes:
      - ./db:/var/lib/mysql
    environment:
      - MYSQL_ROOT_PASSWORD
      - MYSQL_PASSWORD
      - MYSQL_DATABASE
      - MYSQL_USER
