version: "3.5"
services:
  jellyfin:
    image: jellyfin/jellyfin
    container_name: jellyfin
    user: 1000:1000
    volumes:
      - ./config:/config
      - ./cache:/cache
      - /mnt/media:/media
    restart: "unless-stopped"
    ports:
      - 8096:8096
      - 8920:8920
    environment:
      - JELLYFIN_PublishedServerUrl=https://jellyfin.zweili.org
